# 生产环境配置
app:
  # 全局前缀
  prefix: '/api'
  # 启动端口
  port: 3050
  # 开启swagger文档
  swagger: true
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
  # 文件相关
  file:
    # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
    location: '../upload'
    # 文件服务器地址，开发环境
    domain: 'http://localhost:8081'
    # 文件虚拟路径, 必须以 / 开头， 如 http://localhost:8081/static/****.jpg  , 如果不需要则 设置 ''
    serveRoot: '/static'
# 数据库配置
db:
  mysql:
    host: 'localhost'
    username: 'root'
    password: '123456'
    # 数据库名称
    database: 'kapok'
    port: 3306
    charser: 'utf8mb4'
    logger: 'advanced-console'
    logging: true
    multipleStatements: true
    dropSchema: false
    # 根据实体自动创建数据库表， 生产环境建议关闭
    synchronize: false
    supportBigNumbers: true
    bigNumberStrings: true
    # 自动加载实体
    autoLoadEntities: true

# redis 配置
redis:
  host: 'localhost'
  port: 6379
  db: 0
  keyPrefix: 'nest:'

# jwt 配置
jwt:
  secretkey: 'zANDwNQVFzxlfG9myPxVWAkq4iXJEPhI'
  expiresin: '1h'
  refreshExpiresIn: '2h'
# 权限 白名单配置
perm:
  router:
    whitelist:
      [
        { path: '/api/register', method: 'POST' },
        { path: '/api/login', method: 'POST' },
        { path: '/api/perm/{id}', method: 'GET' },
        { path: '/api/oss/upload', method: 'POST' },
      ]

# 用户相关
# 初始密码， 重置密码
user:
  initialPassword: 'Q123456'
